[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pypi-domains-extractor"
version = "0.1.0"
description = "A simple package to extract PyPI domains. Homework for FOSS-dev course."
readme = "README.md"
requires-python = ">=3.8"

[[project.authors]]
name = "Alabaykin"
email = "bells.vtv@gmail.com"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "mypy>=1.0",
    "flake8>=6.0",
    "deptry>=0.12.0",
    "build>=1.0.0",
    "twine>=4.0.0",
]

[project.urls]
Repository = "https://github.com/Alabaykin/test-git-FOSSdev/tree/PypiHW/homeworks/Pypi"

[tool.deptry.per_rule_ignores]
DEP002 = ["pytest", "mypy", "flake8", "deptry", "build", "twine"]
